ingress-nginx:
  controller:
    ingressClassResource:
      name: ingress-nginx
      controllerValue: k8s.io/ingress-nginx
    ingressClass: ingress-nginx
    service:
      type: LoadBalancer
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        # Optional best practice (not required with your Prometheus selectors)
        # additionalLabels:
        #   release: infra-kube-prometheus-stack
