{{- if .Values.clusterIssuer.enabled }}
{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  acme:
    server: {{ .Values.clusterIssuer.server }}
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterIssuer.solver.ingress.class }}
{{- end }}
{{- end }}