apiVersion: v1
kind: Secret
metadata:
  name: kibana-service-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpnQlVDRmRlZFFsZTNQM2ZhUlQxci1R"