apiVersion: v1
kind: Secret
metadata:
  name: kibana-service-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: kibana-sa
type: kubernetes.io/service-account-token
