{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: kibana-service-token
  annotations:
    kubernetes.io/service-account.name: {{ include "kibana.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end -}}